/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizButton {
    }
}
declare global {
    interface HTMLWizButtonElement extends Components.WizButton, HTMLStencilElement {
    }
    var HTMLWizButtonElement: {
        prototype: HTMLWizButtonElement;
        new (): HTMLWizButtonElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-button": HTMLWizButtonElement;
    }
}
declare namespace LocalJSX {
    interface WizButton {
    }
    interface IntrinsicElements {
        "wiz-button": WizButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-button": LocalJSX.WizButton & JSXBase.HTMLAttributes<HTMLWizButtonElement>;
        }
    }
}
